# read_count_multiplier: 0.001
# read_count_prefix: 'K'
# read_count_desc: 'thousands'

extra_fn_clean_exts:
    - '.idxstats'
    - '_stderr'
    - '.gz'
    - '.gatk'
    - '.unmarked'
    - '.trim'
    - 'trimmed'
    - '_umi'
    - '_perfect'
    - '.bam'
    - '.star'
    - '.sort'
    - '.qualimap'
    - '.Log'
    - '.final'
    - '.clump'
    - '.assembled'
    - 'fastq'
    - '.human'
#   - '-'
    - '_1'
    - '_2'
    - '.1'
    - '.2'
    - '_'

fastqscreen_simpleplot: true

remove_sections:
    - samtools-idxstats-xy-counts
    - fastqc_per_base_sequence_content

fn_ignore_files:
    - '*.biotypes.summary'
    - 'Log.final.out'
    - '*.EBV.*'
    - '*.KSHV.*'
    - '*.bw'
    - '*.counts'
    - '*.results'
    - '*multi.count*'

table_columns_visible:
    FastQC:
        percent_duplicates: False
    Rsem:
        alignable_percent: False
    Cutadapt:
        percent_trimmed: False
